### ISSUE TITLE
What is the different from rust-libp2p

### ISSUE THREAD

**Issue by liuyangc3** [nervosnetwork/p2p#198]
https://github.com/libp2p/rust-libp2p

**Comment by driftluo** [comment]
Some on here: https://github.com/nervosnetwork/p2p/blob/master/docs/introduction_en.md#not-compatible-with-libp2p

In the process of development, I have added some new things:

- Flatbuffer may be deprecated in a future release, currently supporting `flatbuffer` or `molecule` handshake serialization in feature mode
- Secio added support `aes-gcm/chacha20ploy1305` encryption algorithm
- Secio `aes-ctr` use the implementation of openssl, ie nonce is 128 bit instead of 64 bit(I think 64bit is bug)

**Comment by liuyangc3** [comment]
Thanks
